service_id=nationalbus
service_url=http://195.12.113.7/bip-sync-wss-gost/
login=techreg
password=Root303q@
keyFile=/opt/service/ktrm/GOST512_66d62764174b71ab656d4afb1449f891a4cafe5a.p12
keyPassword=Aa123456!

server.port=8055
logging.level.root=INFO
logging.level.kz.integration.digisign=DEBUG
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
integration.storage.directory=./zip-request

integration.storage.directory.cert_eaeu=./parent/certEaeu2
integration.storage.directory.decl_eaeu=./parent/declEaeu2
integration.storage.directory.eaue_620=./parent/eaue620_2